### ISSUE TITLE
 Bug suppression d'arme

### ISSUE THREAD

**Issue by kossolax** [ts-x/JAIL#6]
On garde les armes une fois le round fini, alors que nous sommes T et que normalement on devrait les perdre à la fin du round

**Comment by Hellhium** [comment]
Ah c'est corrigé ca, il y avait un true à la place d'un false du coup le terro jetait ses armes au lieu de les perdre, et vu qu'il est dans une cellule il les ramassait de nouveau

**Comment by kossolax** [comment]
:rire:

2017-10-25 9:23 GMT+02:00 SCHNEPP Jemy <notifications@github.com>:
